name: "Lint Arduino Sketch"

on:
  pull_request:
  workflow_dispatch:

jobs:
  arduino-lint:
    name: Lint Arduino Sketch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AutoBoard
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Lint Sketch
        uses: arduino/arduino-lint-action@v1
        with:
          project-type: sketch
          compliance: strict
